// The cue lexicon (ROADMAP.md S8): the words that can say each operator,
// literal, built-in and kind of statement. A cue matches its inflections
// too ("add" matches "adds", "added", "adding"). Tune it against the
// false-rejection metric in the eval report, not by gut feel: every entry
// here makes the validator accept more.

import type {
  ArithmeticOp,
  BoolOpKind,
  CollectionKind,
  CompareOp,
  UnaryOpKind,
  UpdateOp,
} from '@textscript/core';

export const COMPARE_CUES: Readonly<Record<CompareOp, readonly string[]>> = {
  '<': [
    'less',
    'smaller',
    'below',
    'under',
    'fewer',
    'lower',
    'before',
    'shorter',
    'cheaper',
    'until',
    "haven't",
    '<',
    'meet',
    'cross',
    'pass',
    'within',
    'left of',
    'negative',
    'below zero',
  ],
  '<=': [
    'at most',
    'or equal',
    'no more',
    'not more',
    'up to',
    'until',
    'meet',
    'cross',
    'within',
    'less',
    'smaller',
    '<',
    "haven't",
    'not past',
    'through',
  ],
  '>': [
    'greater',
    'bigger',
    'more',
    'larger',
    'above',
    'over zero',
    'exceed',
    'beyond',
    'past',
    'longer',
    'higher',
    'better',
    'beat',
    'positive',
    '>',
  ],
  '>=': [
    'at least',
    'or more',
    'or equal',
    'no less',
    'not less',
    'greater',
    'bigger',
    'more',
    '>',
    'reach',
    'enough',
    'past',
    'cross',
    'at or after',
    'or after',
    'or later',
    'at or',
  ],
  '==': [
    'equal',
    'equals',
    'is',
    'are',
    'same',
    'match',
    'matches',
    'was',
    '=',
    'exactly',
    'hit',
    'land',
    'zero',
    'empty',
    'divisible',
    'even',
    'odd',
    'multiple',
    'only',
    'just',
    'has',
  ],
  '!=': [
    'not',
    "isn't",
    "aren't",
    "doesn't",
    "don't",
    'different',
    'differ',
    'mismatch',
    'other',
    'unequal',
    '!',
    'never',
    'no',
    'wrong',
  ],
};

export const ARITHMETIC_CUES: Readonly<Record<ArithmeticOp, readonly string[]>> = {
  '+': [
    'plus',
    'add',
    'sum',
    'increase',
    'next',
    'after',
    'extend',
    'combine',
    'together',
    'adjacent',
    'neighbor',
    'further',
    '+',
    'including',
    'inclusive',
  ],
  '-': [
    'minus',
    'subtract',
    'less',
    'difference',
    'back',
    'previous',
    'prior',
    'before',
    'distance',
    'width',
    'gap',
    'between',
    'remaining',
    'left',
    'down',
    'take',
    'fewer',
    'behind',
    'need',
    'complement',
    'without',
    'offset',
    'last',
    'profit',
    '-',
    'end',
    'ends',
  ],
  '*': [
    'times',
    'multiply',
    'product',
    'double',
    'twice',
    'area',
    'square',
    'squared',
    'by',
    '*',
    'with',
    'filled',
    'all',
    'every',
    'zeros',
    'ones',
    'entries',
    'copies',
    'length',
    'size',
    'per',
    'slot',
  ],
  '/': ['divide', 'divided', 'over', 'ratio', 'average', 'per', 'half', '/'],
  '//': [
    'divide',
    'divided',
    'half',
    'halve',
    'middle',
    'mid',
    'midpoint',
    'halfway',
    'average',
    'integer',
    'floor',
    'over',
    '/',
  ],
  '%': [
    'mod',
    'modulo',
    'remainder',
    'divisible',
    'divides',
    'even',
    'odd',
    'multiple',
    '%',
    'wrap',
  ],
  '**': ['power', 'squared', 'square', 'cubed', 'exponent', '*'],
};

export const BOOL_CUES: Readonly<Record<BoolOpKind, readonly string[]>> = {
  and: [
    'and',
    'both',
    'also',
    'while',
    'but',
    'as well',
    '&',
    'still',
    'with',
    'nor',
    'in bounds',
    'inside',
    'within',
    'valid',
  ],
  or: ['or', 'either', 'any', '|', 'out of bounds', 'outside', 'otherwise'],
};

export const UNARY_CUES: Readonly<Record<UnaryOpKind, readonly string[]>> = {
  not: [
    'not',
    "isn't",
    "aren't",
    "doesn't",
    "don't",
    "haven't",
    "hasn't",
    "wasn't",
    "can't",
    'no',
    'never',
    'empty',
    'none',
    'nothing',
    'false',
    'without',
    'unseen',
    'unvisited',
    'new',
    'missing',
    'run out',
    'until',
    'fail',
    'invalid',
    'unless',
    '!',
  ],
  '-': ['negative', 'minus', '-', 'infinity', 'last', 'end', 'backwards', 'reverse', 'opposite'],
};

export const MEMBERSHIP_CUES: readonly string[] = [
  'in',
  'contain',
  'contains',
  'seen',
  'exist',
  'exists',
  'has',
  'have',
  'inside',
  'already',
  'among',
  'present',
  'part',
  'within',
  'appear',
  'visited',
  'there',
  'found',
  'key',
  'stored',
  'recorded',
  'saw',
  'met',
  'included',
  'member',
];

export const NEGATION_CUES: readonly string[] = [
  'not',
  "isn't",
  "aren't",
  "doesn't",
  "don't",
  "haven't",
  "hasn't",
  "wasn't",
  "weren't",
  "didn't",
  "can't",
  'no',
  'never',
  'new',
  'unseen',
  'unvisited',
  'missing',
  'absent',
  'first time',
  'without',
  'outside',
  'otherwise',
  'else',
  'unless',
];

export const UPDATE_CUES: Readonly<Record<UpdateOp, readonly string[]>> = {
  '+=': [
    'increment',
    'add',
    'plus',
    'increase',
    'up',
    'bump',
    'more',
    'count',
    'another',
    'extend',
    'grow',
    'accumulate',
    'total',
    'sum',
    'move',
    'step',
    'advance',
    'next',
    'forward',
    'right',
    'shift',
    'one',
    'tally',
    'raise',
    '+',
    'collect',
    'by',
  ],
  '-=': [
    'decrement',
    'subtract',
    'minus',
    'decrease',
    'down',
    'reduce',
    'lower',
    'shrink',
    'less',
    'remove',
    'take',
    'drop',
    'back',
    'left',
    'move',
    'shift',
    'one',
    'use',
    '-',
    'by',
  ],
  '*=': ['times', 'multiply', 'double', 'by', '*'],
  '/=': ['divide', 'halve', 'by', '/'],
  '//=': ['divide', 'halve', 'by', '/'],
  '%=': ['mod', 'modulo', 'remainder', '%'],
  append: [
    'append',
    'add',
    'push',
    'put',
    'insert',
    'record',
    'store',
    'collect',
    'keep',
    'include',
    'save',
    'stick',
    'end',
    'onto',
    'stack',
    'queue',
    'enqueue',
    'list',
    'output',
    'result',
  ],
  extend: ['extend', 'add', 'all', 'concat', 'append', 'merge', 'rest', 'remaining'],
  add: [
    'add',
    'put',
    'insert',
    'mark',
    'record',
    'store',
    'keep',
    'include',
    'remember',
    'track',
    'save',
    'seen',
    'visited',
    'set',
  ],
  remove: ['remove', 'delete', 'drop', 'take', 'pop', 'discard', 'erase', 'evict', 'shrink', 'out'],
  discard: [
    'remove',
    'delete',
    'drop',
    'take',
    'pop',
    'discard',
    'erase',
    'evict',
    'shrink',
    'out',
  ],
};

/** Empty collections: `[]`, `set()`, `()`. */
export const EMPTY_COLLECTION_CUES: Readonly<Record<CollectionKind, readonly string[]>> = {
  list: [
    'empty',
    'list',
    'array',
    'stack',
    'queue',
    'new',
    'blank',
    'result',
    'output',
    'answer',
    'path',
    'nothing',
    'start',
    'collect',
    'lists',
    'buckets',
    'bucket',
    '[',
    'vector',
    'deque',
  ],
  set: [
    'set',
    'empty',
    'seen',
    'visited',
    'unique',
    'distinct',
    'hash',
    'new',
    'window',
    'nothing',
  ],
  tuple: ['tuple', 'pair', 'empty', '('],
};

export const EMPTY_DICT_CUES: readonly string[] = [
  'dict',
  'dictionary',
  'map',
  'hash',
  'hashmap',
  'table',
  'counter',
  'count',
  'counts',
  'lookup',
  'mapping',
  'empty',
  'frequency',
  'index',
  'memo',
  'cache',
  'graph',
  'adjacency',
  'group',
  'groups',
  'bucket',
  'from',
  'to',
  '{',
  'last',
  'seen',
  'where',
];

export const LITERAL_CUES = {
  true: [
    'true',
    'yes',
    'found',
    'exist',
    'valid',
    'is',
    'does',
    'can',
    'possible',
    'success',
    'duplicate',
    'cycle',
    'palindrome',
    'anagram',
    'done',
    'ok',
    'match',
    'reach',
  ],
  false: [
    'false',
    'no',
    'not',
    'never',
    "isn't",
    "can't",
    "doesn't",
    "don't",
    'invalid',
    'fail',
    'nope',
    'impossible',
    'otherwise',
    'else',
    'unvisited',
    'unseen',
    'mismatch',
  ],
  none: [
    'none',
    'null',
    'nothing',
    'empty',
    'no',
    'nil',
    'nobody',
    'missing',
    'previous',
    'prev',
    'end',
    'cut',
    'detach',
    'unset',
    'yet',
    'nowhere',
    'off',
  ],
  emptyString: ['empty', 'blank', 'nothing', 'string', 'join', 'no'],
} as const;

/** Numbers the words can imply without saying them. */
export const NUMBER_CUES: Readonly<Record<number, readonly string[]>> = {
  0: [
    'zero',
    'empty',
    'nothing',
    'start',
    'beginning',
    'first',
    'none',
    'initial',
    'reset',
    'front',
    'origin',
    'clear',
    'ends',
    'only',
    'leftmost',
    'even',
    'divisible',
    'balance',
    'below zero',
    'negative',
  ],
  1: [
    'one',
    'once',
    'single',
    'increment',
    'decrement',
    'another',
    'bump',
    'visiting',
    'last',
    'ends',
  ],
  2: [
    'half',
    'halve',
    'middle',
    'mid',
    'midpoint',
    'halfway',
    'average',
    'double',
    'twice',
    'pair',
    'both',
    'even',
    'odd',
    'second',
    'done',
    'visited',
  ],
  10: ['digit', 'decimal', 'ten'],
  26: ['letter', 'letters', 'alphabet', 'lowercase'],
};

/**
 * Words that imply `+ 1` or `- 1` when said right next to the value:
 * "the next index", "the element before it", "n inclusive".
 */
export const IMPLIED_ONE: readonly string[] = [
  'next',
  'after',
  'before',
  'previous',
  'prior',
  'adjacent',
  'neighbor',
  'inclusive',
  'including',
  'back',
  'following',
  'preceding',
  'through',
];

/** Statements whose kind needs a word. */
export const STATEMENT_CUES = {
  Return: [
    'return',
    'give',
    'answer',
    'output',
    'result',
    'report',
    'send',
    'hand back',
    'done',
    'yield',
  ],
  Break: [
    'break',
    'stop',
    'exit',
    'out',
    'done',
    'quit',
    'leave',
    'end',
    'early',
    'finish',
    'bail',
  ],
  Continue: [
    'continue',
    'skip',
    'next',
    'ignore',
    'move on',
    'pass',
    'nothing',
    'keep going',
    'go on',
    'carry on',
  ],
  If: [
    'if',
    'when',
    'whenever',
    'unless',
    'check',
    'case',
    'only',
    'whether',
    'otherwise',
    'once',
    'else',
    'should',
    'see',
    'until',
    'that',
    'whichever',
    'as long as',
    'while',
  ],
  Elif: ['if', 'when', 'else', 'otherwise', 'elif', 'case', 'unless', 'or'],
  Else: [
    'else',
    'otherwise',
    'if not',
    'instead',
    'or',
    'not',
    'other',
    'no',
    'opposite',
    'rest',
    'every other',
    'remaining',
    'all other',
    'none of',
    'neither',
    'nothing else',
    'anything else',
  ],
  While: [
    'while',
    'until',
    'as long as',
    'keep',
    'loop',
    'repeat',
    'still',
    'till',
    'again',
    'each',
    'every',
    'move',
    'walk',
    'until',
    'whenever',
  ],
  Loop: [
    'for',
    'each',
    'every',
    'loop',
    'iterate',
    'through',
    'over',
    'go',
    'walk',
    'scan',
    'traverse',
    'visit',
    'all',
    'from',
    'range',
    'times',
    'pass',
    'per',
    'step',
  ],
  FunctionDef: [
    'function',
    'def',
    'define',
    'method',
    'helper',
    'recursive',
    'recursion',
    'recurse',
    'dfs',
    'bfs',
    'call',
    'write',
    'takes',
    'returns',
    'solution',
  ],
} as const;

/** Built-in functions and methods: the words that name them. */
export const CALLEE_CUES: Readonly<Record<string, readonly string[]>> = {
  len: [
    'length',
    'len',
    'size',
    'long',
    'many',
    'count',
    'number of',
    'end',
    'last',
    'index',
    'indices',
    'for each',
  ],
  max: [
    'max',
    'maximum',
    'bigger',
    'larger',
    'greater',
    'most',
    'higher',
    'best',
    'longest',
    'more',
    'better',
  ],
  min: [
    'min',
    'minimum',
    'smaller',
    'lesser',
    'least',
    'lower',
    'fewest',
    'shortest',
    'cheapest',
    'less',
    'better',
  ],
  abs: ['absolute', 'abs', 'distance'],
  sum: ['sum', 'total', 'add'],
  sorted: ['sort', 'sorted', 'order', 'ordered', 'smallest', 'largest'],
  sort: ['sort', 'sorted', 'order', 'ordered'],
  range: [
    'range',
    'from',
    'to',
    'through',
    'between',
    'up to',
    'index',
    'indices',
    'times',
    'each',
    'every',
    'loop',
  ],
  enumerate: ['enumerate', 'index', 'indices', 'position', 'positions', 'with'],
  set: ['set', 'unique', 'distinct'],
  list: ['list', 'array'],
  dict: ['dict', 'dictionary', 'map'],
  int: ['int', 'integer', 'number', 'digit', 'whole'],
  str: ['str', 'string', 'text'],
  ord: ['ord', 'code', 'ascii', 'letter', 'character', 'position', 'index', 'alphabet'],
  chr: ['chr', 'char', 'character', 'letter'],
  reversed: ['reverse', 'reversed', 'backwards', 'back'],
  zip: ['zip', 'pair', 'together', 'alongside', 'side by side'],
  any: ['any', 'some', 'exists'],
  all: ['all', 'every', 'each'],
  print: ['print', 'output', 'show'],
  float: ['float', 'infinity', 'inf', 'decimal'],
  deque: ['deque', 'queue', 'double'],
  defaultdict: ['default', 'dictionary', 'dict', 'map', 'group', 'list'],
  Counter: ['count', 'counter', 'frequency', 'frequencies', 'tally'],
  heappush: ['push', 'add', 'heap', 'insert', 'put'],
  heappop: ['pop', 'remove', 'take', 'smallest', 'heap', 'evict'],
  heapify: ['heap', 'heapify'],
  heapq: ['heap'],
  isalnum: ['alphanumeric', 'letter', 'digit', 'alnum', 'character'],
  isalpha: ['letter', 'alpha', 'alphabetic'],
  isdigit: ['digit', 'number', 'numeric'],
  lower: ['lower', 'lowercase', 'case'],
  upper: ['upper', 'uppercase', 'case'],
  pop: ['pop', 'remove', 'take', 'top', 'last', 'off', 'drop'],
  popleft: ['pop', 'remove', 'front', 'first', 'left', 'take', 'dequeue', 'off', 'drop'],
  append: ['append', 'add', 'push', 'put', 'record', 'store', 'collect', 'keep'],
  appendleft: ['append', 'add', 'push', 'front', 'left'],
  get: ['get', 'look', 'lookup', 'count', 'default', 'value', 'or', 'zero', 'so far'],
  items: ['items', 'pairs', 'entries', 'each', 'key', 'value'],
  keys: ['keys', 'key'],
  values: ['values', 'value', 'groups', 'buckets', 'lists'],
  join: ['join', 'concatenate', 'combine', 'together', 'string', 'key'],
  split: ['split', 'break', 'words'],
  index: ['index', 'position', 'where'],
  count: ['count', 'how many', 'number of'],
  add: ['add', 'put', 'insert', 'mark', 'record', 'store', 'set', 'seen', 'visited'],
  remove: ['remove', 'delete', 'drop', 'take', 'out'],
  discard: ['remove', 'delete', 'drop', 'take', 'out', 'discard'],
  extend: ['extend', 'add', 'all'],
  insert: ['insert', 'add', 'put'],
  copy: ['copy', 'snapshot', 'clone'],
  isinstance: ['type', 'kind', 'is a'],
  tuple: ['tuple', 'pair', 'key', 'sorted'],
};

/** Single-letter and common short names: the words that can say them. */
export const NAME_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  i: ['index', 'indices', 'position', 'idx', 'i'],
  j: ['index', 'indices', 'position', 'j', 'second', 'inner', 'other'],
  k: ['k', 'index', 'key'],
  n: ['n', 'length', 'size', 'count', 'number', 'total', 'how many', 'len'],
  m: ['m', 'rows', 'columns', 'length', 'size'],
  s: ['s', 'string', 'str', 'text'],
  t: ['t', 'string', 'other'],
  c: ['c', 'char', 'character', 'letter', 'column', 'col', 'cell'],
  ch: ['char', 'character', 'letter', 'ch'],
  x: ['x', 'value', 'element', 'item', 'number', 'it'],
  r: ['r', 'row', 'right'],
  l: ['l', 'left'],
  q: ['q', 'queue'],
  dq: ['deque', 'queue', 'dq'],
  dp: ['dp', 'table', 'dynamic', 'ways', 'best', 'answer', 'memo'],
  res: ['result', 'answer', 'output'],
  ans: ['answer', 'result', 'output'],
  out: ['output', 'result', 'answer', 'out'],
  key: ['key', 'signature', 'sorted', 'id'],
  val: ['value', 'val'],
  node: ['node', 'it', 'current'],
  prev: ['previous', 'prev', 'before', 'behind'],
  curr: ['current', 'curr', 'cur', 'node'],
  cur: ['current', 'curr', 'cur', 'node'],
  nxt: ['next', 'nxt'],
  tmp: ['temporary', 'temp', 'tmp'],
  mid: ['middle', 'mid', 'midpoint', 'halfway'],
  lo: ['low', 'lo', 'left', 'start'],
  hi: ['high', 'hi', 'right', 'end'],
  w: ['width', 'w', 'word'],
  h: ['height', 'h'],
};

/** Words that refer to something already set up without naming it. */
export const REFERENCE_WORDS: readonly string[] = [
  'it',
  'its',
  "it's",
  'that',
  'this',
  'them',
  'they',
  'those',
  'these',
  'one',
  'ones',
  'there',
  'which',
  'itself',
  'current',
  'element',
  'item',
  'value',
  'number',
  'thing',
  'entry',
  'each',
  'every',
  'character',
  'char',
  'letter',
  'word',
  'node',
  'answer',
  'result',
  'everything',
  'him',
  'her',
  'same',
  'whatever',
  'the',
  'his',
];

/** Words that can refer to one of the problem's inputs. */
export const INPUT_WORDS: readonly string[] = [
  'input',
  'given',
  'array',
  'list',
  'string',
  'sequence',
  'collection',
  'numbers',
  'values',
  'elements',
  'items',
  'grid',
  'matrix',
  'tree',
  'root',
  'head',
  'prices',
  'intervals',
  'target',
  'nums',
  'it',
  'them',
  'all',
  'whole',
  'entire',
];

/** Strings named by a word rather than said literally. */
export const STRING_CUES: Readonly<Record<string, readonly string[]>> = {
  '(': ['paren', 'parenthesis', 'parentheses', 'round', 'open', 'bracket'],
  ')': ['paren', 'parenthesis', 'parentheses', 'round', 'close', 'bracket'],
  '[': ['square', 'bracket', 'open'],
  ']': ['square', 'bracket', 'close'],
  '{': ['curly', 'brace', 'bracket', 'open'],
  '}': ['curly', 'brace', 'bracket', 'close'],
  ' ': ['space', 'spaces', 'blank'],
  '#': ['hash', 'pound', 'separator', 'delimiter', 'marker'],
  ',': ['comma', 'separator'],
  '1': ['land', 'one', 'island'],
  '0': ['water', 'zero'],
};
